### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Sakarias-Longhorn** [Wurielle/clarence#1]
Hello,

When I start Clarence, it shows the following error : 
![](http://i.imgur.com/DIS4Ksn.png)

Windows 10 Pro x64

Best regards.

**Comment by Wurielle** [comment]
There's a new release that should fix the problem! Let me know if it is working for you. :)

**Comment by Sakarias-Longhorn** [comment]
Fixed for me, thanks !
